---
driver:
  name: dokken

transport:
  name: dokken

provisioner:
  name: dokken
  always_update_cookbooks: true

verifier:
  root_path: '/opt/verifier'
  sudo: false

platforms:
- name: centos-7
  driver:
    image: dokken/centos-7

suites:
  - name: default
    run_list:
      - recipe[sensu::default]
    attributes:
